org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.configuration-cache=false
minecraft_version=26.1.2
neo_version=26.1.2.114
mod_id=slashblade
mod_name=Slash Blade
mod_version=0.1.2-26.1.2-port.25
mod_group_id=mods.flammpfeil.slashblade
mod_license=NyMmd-MIT:nyatla, ObjModelImporter:forge, All other Rights reserved.
